### ISSUE TITLE
Help[SOLVED]

### ISSUE THREAD

**Issue by z0mbooy** [RandomBananazz/AutoWaifuClaimer#5]
Hello very good, a query, when opening the bot.py file, it opens and closes altiro, are you ready ?, I am new to this

**Comment by z0mbooy** [comment]
![image](https://user-images.githubusercontent.com/69091705/89448668-f6a52000-d725-11ea-81d0-eee250400bcc.png)
 
It's OK now?

**Comment by niqitowo** [comment]
Bro, me explicas como hiciste?

**Comment by yisusmoises** [comment]
lo mismo pido
